"""
Django settings for OAback project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

from .config import Core, Databases, Email, Celery, Caches

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = Core.SECRET_KEY

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = Core.DEBUG

ALLOWED_HOSTS = Core.ALLOWED_HOSTS


# Application definition

INSTALLED_APPS = [
    # 'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    # 'django.contrib.sessions',
    # 'django.contrib.messages',
    'django.contrib.staticfiles',


    #安装DRF
    "rest_framework",
    # 项目的APP
    'APPS.oaauth.apps.OaauthConfig',
    'APPS.absent.apps.AbsentConfig',
    'APPS.inform.apps.InformConfig',
    'APPS.staff.apps.StaffConfig',
    'APPS.image.apps.ImageConfig',
    'APPS.agent.apps.AgentConfig'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # 'django.contrib.sessions.middleware.SessionMiddleware',

    #一定要在CommonMiddleware前面
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    #关闭CSRF
    # 'django.middleware.csrf.CsrfViewMiddleware',
    # 'django.contrib.auth.middleware.AuthenticationMiddleware',
    # 'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "APPS.oaauth.middlewares.LoginCheckMiddleware"
]

ROOT_URLCONF = 'OAback.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                # 'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'OAback.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': Databases.ENGINE,
        'NAME': Databases.NAME,
        "USER": Databases.USER,
        "PASSWORD": Databases.PASSWORD,
        "HOST": Databases.HOST,
        "PORT": Databases.PORT,
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / "static"
]

# 生产环境 collectstatic 收集目录（部署时执行 manage.py collectstatic）
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_ROOT = BASE_DIR/"media"
MEDIA_URL = "/media/"


# 允许所有域名跨域访问
CORS_ALLOW_ALL_ORIGINS=True

#覆盖Django附带的User模型
# 语法：app.User模型名
#错误写法：
# AUTH_USER_MODEL = "apps.oaauth.OAUser"
#正确写法：
AUTH_USER_MODEL = "oaauth.OAUser"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": ["APPS.oaauth.authentications.UserTokenAuthentication"],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
}

"""邮箱验证码配置"""
EMAIL_BACKEND = Email.EMAIL_BACKEND
EMAIL_USE_TLS = Email.EMAIL_USE_TLS
EMAIL_HOST = Email.EMAIL_HOST
EMAIL_PORT = Email.EMAIL_PORT
EMAIL_HOST_USER = Email.EMAIL_HOST_USER
EMAIL_HOST_PASSWORD = Email.EMAIL_HOST_PASSWORD
DEFAULT_FROM_EMAIL = Email.DEFAULT_FROM_EMAIL


"""CELERY相关配置"""
# 中间人的配置
CELERY_BROKER_URL = Celery.CELERY_BROKER_URL
# 指定结果的接受地址
CELERY_RESULT_BACKEND = Celery.CELERY_RESULT_BACKEND



"""缓存设置"""
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": Caches.LOCATION,
    }
}


"""日志"""
import os

# 日志级别：开发环境打全量 SQL，生产环境只打 INFO 及以上（避免刷爆日志文件）
LOG_LEVEL = "DEBUG" if Core.DEBUG else "INFO"

# 日志目录：默认项目根 logs/ 并自动创建；服务器部署时可用环境变量 LOG_DIR 覆盖（如 /data/log）
LOG_DIR = Path(os.environ.get("LOG_DIR", str(BASE_DIR / "logs")))
Path(LOG_DIR).mkdir(parents=True, exist_ok=True)

LOGGING = {
    "version": 1,
    'disable_existing_loggers': True,
    'formatters': {
        'verbose': {
            'format': '%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s'
        },
        'simple': {
            'format': '%(levelname)s %(message)s'
        },
    },
    'handlers': {
        'console':{
            'level': LOG_LEVEL,
            'class': 'logging.StreamHandler',
            'formatter': 'verbose'
        },
       'file': {
           'level': LOG_LEVEL,
           'class': 'logging.FileHandler',
           'filename': str(LOG_DIR / 'oa.log'),
           'formatter': 'verbose'
       },
    },
    'loggers': {
        'django': {
            'handlers': ['console','file'],
            'level': LOG_LEVEL,
        },
    },
}