# Generated by Django 6.0.4 on 2026-07-06 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('absent', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='absent',
            options={'ordering': ('-create_time',)},
        ),
    ]
